# Generated by Django 2.0.1 on 2018-01-22 12:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sua.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='申诉日期')),
                ('claim', models.CharField(max_length=400)),
                ('reason', models.CharField(blank=True, max_length=400)),
                ('is_passed', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('feedback', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='GSua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='活动日期')),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GSuaPublicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=400)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('published_begin_date', models.DateTimeField(default=datetime.datetime(2018, 1, 22, 20, 48, 16, 510756), verbose_name='开始公示时间')),
                ('published_end_date', models.DateTimeField(verbose_name='结束公示时间')),
                ('gsua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sua.GSua')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.IntegerField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='生成日期')),
                ('is_offline', models.BooleanField(default=False)),
                ('proof_file', models.FileField(blank=True, storage=sua.storage.FileStorage(), upload_to='proofs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Student Number')),
                ('suahours', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2018, verbose_name='Student Grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='活动日期')),
                ('suahours', models.FloatField()),
                ('last_time_suahours', models.FloatField(default=0.0)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sua_Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='申请日期')),
                ('detail', models.CharField(max_length=400)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('is_checked', models.BooleanField(default=False)),
                ('feedback', models.CharField(blank=True, max_length=400)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sua.Proof')),
                ('sua', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sua.Sua')),
            ],
        ),
        migrations.CreateModel(
            name='SuaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('rank', models.IntegerField(blank=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='sua',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sua.SuaGroup'),
        ),
        migrations.AddField(
            model_name='sua',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sua.Student'),
        ),
        migrations.AddField(
            model_name='gsua',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sua.SuaGroup'),
        ),
        migrations.AddField(
            model_name='gsua',
            name='suas',
            field=models.ManyToManyField(to='sua.Sua'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='gsua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sua.GSua'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sua.Student'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='sua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sua.Sua'),
        ),
    ]
