# Generated by Django 2.0.1 on 2018-03-01 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project.sua.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=400)),
                ('group', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='活动日期')),
                ('is_valid', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('content', models.CharField(blank=True, max_length=400)),
                ('status', models.IntegerField(default=0)),
                ('is_checked', models.BooleanField(default=False)),
                ('feedback', models.CharField(blank=True, max_length=400)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('is_checked', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('feedback', models.CharField(blank=True, max_length=400)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.IntegerField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_offline', models.BooleanField(default=False)),
                ('proof_file', models.FileField(blank=True, storage=project.sua.storage.FileStorage(), upload_to='proofs')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=400)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('begin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始公示时间')),
                ('end', models.DateTimeField(verbose_name='结束公示时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicities', to='sua.Activity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Student Number')),
                ('suahours', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('classtype', models.CharField(max_length=100)),
                ('grade', models.IntegerField(choices=[(2016, 2016), (2017, 2017)], default=2018, verbose_name='Student Grade')),
                ('phone', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('team', models.CharField(max_length=100)),
                ('suahours', models.FloatField()),
                ('added', models.FloatField(default=0.0)),
                ('is_valid', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suas', to='sua.Activity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suas', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suas', to='sua.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SuaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('rank', models.IntegerField(blank=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='proof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='sua.Proof'),
        ),
        migrations.AddField(
            model_name='application',
            name='sua',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='sua.Sua'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='publicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='sua.Publicity'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='sua.Student'),
        ),
    ]
